# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-FastProf
version:      0.01
version_from: lib/Devel/FastProf.pm
installdirs:  site
requires:
    Sort::Key:                     0.13
    Time::HiRes:                   1.74

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
