--- #YAML:1.0
name:                Devel-FastProf
version:             0.06
abstract:            "fast" perl per-line profiler
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Sort::Key:                     1.01
    Time::HiRes:                   1.74
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Salvador Fandino <sfandino@yahoo.com>
